---
- name: Install packages
  apt:
    name:
      - vim
      - neofetch
    state: present
- name: Remove packages
  apt:
    name:
      - lighttpd
      - mini-httpd
      - nano
    state: absent
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
- name: Update MOTD
  template:
    src: 01-neofetch.j2
    dest: /etc/update-motd.d/01-neofetch
    owner: root
    group: root
    mode: 0755