---

- hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: k3s_cluster/reset
      become: true
    - role: k3s_cluster/raspberrypi
      become: true
      vars: {state: absent}
  post_tasks:
    - name: Reboot and wait for node to come back up
      become: true
      reboot:
        reboot_timeout: 3600

- hosts: proxmox
  gather_facts: true
  become: true
  remote_user: "{{ proxmox_lxc_ssh_user }}"
  roles:
    - role: k3s_cluster/reset_proxmox_lxc
      when: proxmox_lxc_configure
