---

- hosts: proxmox
  gather_facts: true
  become: true
  roles:
    - role: k3s_cluster/proxmox_lxc
      when: proxmox_lxc_configure

- hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: k3s_cluster/lxc
      become: true
      when: proxmox_lxc_configure
    - role: k3s_cluster/prereq
      become: true
    - role: k3s_cluster/download
      become: true
    - role: k3s_cluster/raspberrypi
      become: true

- hosts: master
  vars_files: ../vars/vault.yaml
  roles:
    - role: k3s_cluster/k3s/master
      become: true

- hosts: node
  roles:
    - role: k3s_cluster/k3s/node
      become: true

- hosts: master
  roles:
    - role: k3s_cluster/k3s/post
      become: true
